# Name of the workflow
name: CI

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request_target:
    branches:
      - main  # Trigger on pull request to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      node_version:
        description: 'Node.js version to use'
        required: true
        default: '22.x'
      upload_report:
        description: 'Upload Allure HTML report'
        required: true
        default: 'true'

# Define the jobs to run as part of the workflow
jobs:
  build:
    # Specify the environment to run the job
    runs-on: ubuntu-latest

    # Define a matrix of Node.js versions to test against
    strategy:
      matrix:
        node-version: ${{ inputs.node_version }}  # Use the Node.js version from the inputs

    # Define the steps to run in the job
    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}  # Use the Node.js version from the matrix

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install  # Run npm install to install dependencies

    # Step 4: Run tests (conditionally)
    - name: Run tests
      run: npm run test:github  # Run npm test to execute the tests

    # Step 5: Upload Allure HTML report (conditionally)
    - name: Upload Allure HTML report
      if: ${{ inputs.upload_report == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: allure-html-report  # Name of the artifact
        path: allure-report  # Path to the Allure HTML report